jwtTokenSecret: dfwzsdzwh823zebdwdz772632gdsbdefigh34ty73gfh34uifh34f

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:/Users/gabriel.candal/paymentapi/target

server:
  rootPath: /api/v1

logging:
  level: INFO
  loggers:
    gcandal.expensetracker: DEBUG
    io.dropwizard: DEBUG
    org.hibernate.SQL:
      level: DEBUG
  appenders:
    - type: console
